// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz2EzdH6_C-pp_F5Z0XcqjdHGZxEX0cNw',
    appId: '1:411285618782:web:54276b1e18c6246c0e34cf',
    messagingSenderId: '411285618782',
    projectId: 'smart-parking-22920',
    authDomain: 'smart-parking-22920.firebaseapp.com',
    storageBucket: 'smart-parking-22920.appspot.com',
    measurementId: 'G-XQGQCCFFS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EDF4MnYGKxlUOxCS0KrWti_0-A0iq4E',
    appId: '1:411285618782:android:dcdc999fd0c8ca050e34cf',
    messagingSenderId: '411285618782',
    projectId: 'smart-parking-22920',
    storageBucket: 'smart-parking-22920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARQgDoLmdcxOXEgnROAx7ZQTzg-EAAX8',
    appId: '1:411285618782:ios:77b0ba372a68e6aa0e34cf',
    messagingSenderId: '411285618782',
    projectId: 'smart-parking-22920',
    storageBucket: 'smart-parking-22920.appspot.com',
    iosBundleId: 'com.example.aws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDARQgDoLmdcxOXEgnROAx7ZQTzg-EAAX8',
    appId: '1:411285618782:ios:77b0ba372a68e6aa0e34cf',
    messagingSenderId: '411285618782',
    projectId: 'smart-parking-22920',
    storageBucket: 'smart-parking-22920.appspot.com',
    iosBundleId: 'com.example.aws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz2EzdH6_C-pp_F5Z0XcqjdHGZxEX0cNw',
    appId: '1:411285618782:web:314c22284aa96f480e34cf',
    messagingSenderId: '411285618782',
    projectId: 'smart-parking-22920',
    authDomain: 'smart-parking-22920.firebaseapp.com',
    storageBucket: 'smart-parking-22920.appspot.com',
    measurementId: 'G-2EKY0B6TZZ',
  );
}
